Resources:
  iamrole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          -
            Effect: "Allow"
            Action:
              - "sts:AssumeRole"
            Principal:
              Service:
                - "cloudformation.amazonaws.com"
      Path: "/"
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/AdministratorAccess" # this would be tighter in production
Outputs:
  stackrole:
    Description: Stack Role arn
    Value: !GetAtt iamrole.Arn
